using MahApps.Metro.Controls;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace OpenPomodoro
{
    /// <summary>
    /// Interaction logic for PauseAdvices.xaml
    /// </summary>
    public partial class PauseAdvices : MetroWindow, INotifyPropertyChanged
    {
        public PauseAdvices()
        {
            InitializeComponent();
        }

        public event PropertyChangedEventHandler PropertyChanged; // TODO: WTF??

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

            try
            {
                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "Probability").FirstOrDefault().Visibility = Visibility.Collapsed;
                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "LastSeen").FirstOrDefault().Visibility = Visibility.Collapsed;

                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "Content").FirstOrDefault().IsReadOnly = true;
                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "Content").FirstOrDefault().Width = 900;
            }
            catch (Exception) { }


        }
    }

}
